### PR TITLE
add openbsd/amd64 support

### PR DESCRIPTION
**Pull request by jcs**

### CODE REVIEW

**Comment by jcs** [comment]
FWIW, this was developed and tested on OpenBSD with the `crypto/ssh` package and has been in production for a while.

**Comment by jcs** [comment]
Ping?

**Comment by creack** [comment]
@jcs Sorry, I didn't have a lot of time lately, I still need to spin up an openbsd VM to test it. I'll try to make it happen this week.

**Comment by creack** [comment]
Closed in favor of  #58 @jcs please take a look.

**Pull request closed without merging**
